---
- name: Configure web server hosts
  hosts: managedhost1
  vars:
    firewall_pkg: firewalld
    firewall_svc: firewalld
    web_pkg: httpd
    web_svc: httpd
    ssl_pkg: mod_ssl
    httpdconf_src: files/httpd.conf
    httpdconf_dest: /etc/httpd/conf/httpd.conf
    htaccess_src: files/.htaccess
    secrets-dir: /etc/httpd/secrets
    secrets_src: files/htpasswd
    secrets_dest: "{{ secrets_dir }}/htpasswd"
    web_root: /var/www/html
  tasks:
    - name: latest versions of packages installed
      ansible.builtin.dnf:
        name: 
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: latest
    - name: Ensure file exists
      ansible.builtin.copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_dest }}"
        owner: root
        group: root
        mode: 0644
    - name: Create {{ secrets_dir }}
      ansible.builtin.file
        path: "{{ secrets_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: 0500
    - name: Create htpasswd file
      ansible.builtin.copy:
        src: "{{ secrets_src }}"
        dest: "{{ secrets_dest }}"
        owner: apache
        group: apache
        mode: 0400
    - name: Create .htacces file
      ansible.builtin.copy:
        src: "{{ htaccess_src }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: 0400
    - name: Create index.html file
      ansible.builtin.copy:
        content: |
          "{{ ansible_facts['hostname'] (ansible_facts['default_ipv4']['address']
          has been customized by Ansible"
        dest: "{{ web_root }}index.html"
    - name: Start firewall service
      ansible.builtin.service:
        name: "{{ firewall_svc }}"
        state: started
        enabled: true
    - name: Enable https service
      ansible.posix.firewalld:
        service: https 
        state: enabled
        immediate: true
        permanent: true
    - name: Enable web service
      ansible.builtin.service:
        name: "{{ web_svc }}"
        state: started
        enabled: true

- name: Test web server authentication
  hosts: localhost
  become_user: no
  vars:
    web_user: guest
  vars_files:
    - vars/secret.yml
  tasks: 
    - name: Request content
      ansible.builtin.uri:
        url: https://serverb.lab.example.com
        validate_certs: no
        force_basic_auth: yes
        user: "{{ web_user }}"
        password: "{{ web_pass }}"
        status_code: 200
        return_content: yes
      register: auth_test

    - name: Print auth_test content
      ansible.builtin.debug:
        var: auth_test.content
