---
- name: Use Jinja2 template for /etc/hosts creation
  hosts: all
  remote_user: root
  tasks:
    - name: update /hosts.j2
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
      
