---
- name: Use Jinja2 template for /etc/hosts creation
  hosts: all
  remote_user: root
  tasks:
    - name: update /home/ansible/hosts.j2
      template:
        src: https://github.com/Glowry2022/ansible/blob/main/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
      
