---
- name: Check httpd status
  hosts: all
  tasks:
    - name: Check httpd status
      command: systemctl status httpd
      register: result

    - name: Display http status
      debug:
        var: result
