---
- name: Test magic var hosts_vars
  tasks:
    - name: Print list of network interfaces for managedhost1
      ansible.builtin.debug:
        var: hostvars['managedhost1']['ansible_facts']['interfaces']

